
title: Question2Answer
subTitle: Free and open source platform for Q&A sites

menu:
    items:
        home:
            text: Intro
            url: /
        install:
            text: Install
            url: /install/basic/
            subitems:
                wordpress:
                    text: Wordpress
                    url: /install/wordpress/
                sso:
                    text: Single Sign-On
                    url: /install/single-sign-on/
                optimization:
                    text: Optimization
                    url: /install/optimization/
                security:
                    text: Security
                    url: /install/security/
        translate:
            text: Translate
            url: /translate/
        themes:
            text: Themes
            url: /themes/
        plugins:
            text: Plugins
            url: /plugins/overview/
            subitems:
                metadata:
                    text: Plugin Metadata
                    url: /plugins/metadata/
                page:
                    text: Page Plugins
                    url: /install/page/
                login:
                    text: Login Plugins
                    url: /install/login/
                editor:
                    text: Editor Plugins
                    url: /install/editor/
                viewer:
                    text: Viewer Plugins
                    url: /install/viewer/
        config:
            text: Configuration
            url: /install/config/
