
title: Question2Answer
subTitle: Free and open source platform for Q&A sites

menu:
    items:
        home:
            text: Intro
            url: /
        install:
            text: Install
            url: /install/basic/
            subitems:
                wordpress:
                    text: Wordpress
                    url: /install/wordpress/
                sso:
                    text: Single Sign-On
                    url: /install/single-sign-on/
                optimization:
                    text: Optimization
                    url: /install/optimization/
                security:
                    text: Security
                    url: /install/security/
        config:
            text: Configuration
            url: /install/config/
        plugin-metadata:
            text: Plugin Metadata
            url: /plugins/metadata/
